{
  State.mag
  Utils.mag
  ArgSpec.mag
  Timer.mag
  Subgrpcls.mag
  Subgrpcls2.mag
  Attr.mag
  Iter.mag
  Expr.mag
  GrpPerm.mag
  HomGrpPerm.mag
  Conj.mag
  GloMod.mag
  Stat.mag
  GaloisGroup.mag
  GaloisGroup_Tame.mag
  GaloisGroup_Builtin.mag
  GaloisGroup_SinglyRamified.mag
  GaloisGroup_ARM.mag
  GaloisGroup_Sequence.mag
  GaloisGroup_Recursive.mag
  Tranche.mag
  Stream.mag
  ResGroups.mag
  ResChoice.mag
  ResEval.mag
  ResPriority.mag
  Field.mag
  PolRing.mag
  SubgrpDedupe.mag
  UpTo.mag
}