174,0
V,OM,6
S,AbsoluteNorm,The absolute norm of g,0,1,0,0,0,0,0,0,0,312,,312,-38,-38,-38,-38,-38
S,elt_recformat,,0,0,0,0,0,0,0,-1,-38,-38,-38,-38,-38
S,elt_print,,0,1,0,0,1,0,0,0,0,-1,,-38,-38,-38,-38,-38,-38
S,elt_with_val,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_val,find the valuation of A and a reduced elt B with A~B. Return B as an elt,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_to_poly,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_from_poly,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_pow_raw,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_mult_raw,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_mult,A*B,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_residue,A mod p as an element of O,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,elt_mult_unit,,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,frame_recformat,,0,0,0,0,0,0,0,-1,-38,-38,-38,-38,-38
S,OmFirstFrame,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,prev_frame,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,segment_recformat,,0,0,0,0,0,0,0,-1,-38,-38,-38,-38,-38
S,OmSegments,Return the list of segments of the newton polygon of phi,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmNextFrames,the next frames,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,om_next_phi,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,om_tree_sub,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmTree,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmIndex,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmLift,"Lift an approximation to an irreducible factor, to a factor with precision nu",0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmSingleFactor,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmDefiningPolynomial,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,reduce_poly,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OptimizedUnramifiedExtension,unramified extension of degree F of R,0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OptimizedTamelyRamifiedExtension,tamely ramified extension of R given by x^E0+C,0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OptimizedWildlyRamifiedExtension,"An optimized representation of the wildly ramified extension of R generated by PHI, i.e., as a wildly ramified extension over a tamely ramified extension over an unramifed extension of Zp",0,2,0,0,0,0,0,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,om_splitting_sub,,0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,om_splitting_start,,0,3,0,0,0,0,0,0,0,-1,,0,0,-1,,0,0,-1,,-1,-38,-38,-38,-38,-38
S,OmSplittingField,,0,1,0,0,0,0,0,0,0,-1,,-1,-38,-38,-38,-38,-38
